version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./pomodorotimer:/home/node/app/pomodorotimer
    container_name: vs-code-extension
    command: tail -f /dev/null