<?php
/**
 * PostItemApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  App\UI\HTTP\REST
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * API REST Todo - OpenAPI 3.0
 *
 * Spec API pour le projet Todo.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace App\UI\HTTP\REST\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\UI\HTTP\REST\Model\Error;
use App\UI\HTTP\REST\Model\Item;
use App\UI\HTTP\REST\Model\PostItemRequest;

/**
 * PostItemApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  App\UI\HTTP\REST\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface PostItemApiInterface
{

    /**
     * Operation createItem
     *
     * Create item for a list
     *
     * @param  PostItemRequest $postItemRequest  Create a new item in the list (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function createItem(
        PostItemRequest $postItemRequest,
    ): array|object|null;
}
