services:
  App\Infrastructure\Validator\SymfonyValidator\PostItemValidator: ~

  App\Domain\SPI\Validator\PostItemValidatorInterface: '@App\Infrastructure\Validator\SymfonyValidator\PostItemValidator'