version: '3.3'

services:
  todo-ui-vue:
    build:
      context: "~/Projets/vscode-extension-pomodoro/ui/vue/"
      tags:
        - "todo-ui-vue:dev"
    env_file:
      - .env
    container_name: todo-ui-vue"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - "traefik.http.routers.${PROJECT_NAME}_web.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_web.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_websecure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_websecure.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_websecure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_websecure.tls.certresolver=le"
    volumes:
      - ~/Projets/vscode-extension-pomodoro/ui/vue:/home/node/app
    networks:
      - web
      - todo_app
      - "${PROJECT_NAME}"
    expose:
      - '3600'
    ports:
      - '3600:4000'
    command: npm run dev

networks:
  web:
    name: web
    external: true
  todo_app:
    name: todo_app
    external: true
  todo_ui_vue:
    driver: bridge
    name: "${PROJECT_NAME}"
